# Generated by Django 2.2.4 on 2019-08-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mavenartifact',
            options={'default_related_name': '%(app_label)s_%(model_name)s'},
        ),
        migrations.AlterModelOptions(
            name='mavendistribution',
            options={'default_related_name': '%(app_label)s_%(model_name)s'},
        ),
        migrations.AlterModelOptions(
            name='mavenremote',
            options={'default_related_name': '%(app_label)s_%(model_name)s'},
        ),
        migrations.AlterField(
            model_name='mavenartifact',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='maven_mavenartifact', serialize=False, to='core.Content'),
        ),
        migrations.AlterField(
            model_name='mavendistribution',
            name='basedistribution_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='maven_mavendistribution', serialize=False, to='core.BaseDistribution'),
        ),
        migrations.AlterField(
            model_name='mavenremote',
            name='remote_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='maven_mavenremote', serialize=False, to='core.Remote'),
        ),
    ]
