# Generated by Django 5.2.15 on 2026-06-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_artifact_artifact_domain_size_index'),
        ('maven', '0007_alter_mavenartifact_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MavenPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.publication')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.publication',),
        ),
        migrations.AddField(
            model_name='mavenrepository',
            name='autopublish',
            field=models.BooleanField(default=False),
        ),
    ]
