# Generated by Django 5.2.16 on 2026-07-21 12:53

import django.db.models.deletion
import pulpcore.app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maven", "0009_remove_publications"),
    ]

    operations = [
        migrations.CreateModel(
            name="MavenPackage",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("group_id", models.CharField(max_length=255)),
                ("artifact_id", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=255)),
                ("name", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("packaging", models.CharField(max_length=64, null=True)),
                ("url", models.CharField(max_length=2048, null=True)),
                ("licenses", models.JSONField(null=True)),
                ("dependencies", models.JSONField(null=True)),
                ("scm_url", models.CharField(max_length=2048, null=True)),
                (
                    "_pulp_domain",
                    models.ForeignKey(
                        default=pulpcore.app.util.get_domain_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.domain",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("group_id", "artifact_id", "version", "_pulp_domain")},
            },
            bases=("core.content",),
        ),
    ]
