# Generated by Django 5.2.17 on 2026-09-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0014_mavenpackage_trgm_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MavenDirectoryState',
            fields=[
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maven.mavenrepository')),
                ('version_id', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MavenDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('path_hash', models.CharField(max_length=64)),
                ('page_id', models.UUIDField(null=True)),
                ('page_sha256', models.CharField(blank=True, max_length=64)),
                ('dirty', models.BooleanField(default=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maven.mavenrepository')),
            ],
        ),
        migrations.CreateModel(
            name='MavenDirectoryChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content_id', models.UUIDField(null=True)),
                ('size', models.BigIntegerField(null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maven.mavendirectory')),
            ],
        ),
        migrations.AddIndex(
            model_name='mavendirectory',
            index=models.Index(condition=models.Q(('dirty', True)), fields=['repository'], name='maven_dirty_directories'),
        ),
        migrations.AddConstraint(
            model_name='mavendirectory',
            constraint=models.UniqueConstraint(fields=('repository', 'path_hash'), name='maven_directory_path'),
        ),
        migrations.AddConstraint(
            model_name='mavendirectorychild',
            constraint=models.UniqueConstraint(fields=('directory', 'name'), name='maven_directory_child'),
        ),
    ]
